codecov:
  notify:
    after_n_builds: 1
  require_ci_to_pass: true

comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: false
  require_changes: false
  require_head: true

coverage:
  precision: 2
  range:
    - 40.0
    - 100.0
  round: down
  status:
    patch:
      default:
        target: 40.0
        threshold: 5.0
    project:
      default:
        informational: false
        target: 40.0
        threshold: 1.0

ignore:
  - "tmp/**/*"
  - "build/**/*"
  - "**/*_test.go"

parsers:
  go:
    partials_as_hits: true
