// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assertions.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const acceptAssertionCounter = `-- name: AcceptAssertionCounter :exec
UPDATE authenticators SET sign_count = $2, backup_state = $3, credential_data = $4, replay_revision = replay_revision + 1 WHERE id = $1
`

type AcceptAssertionCounterParams struct {
	ID             string `json:"id"`
	SignCount      int64  `json:"sign_count"`
	BackupState    bool   `json:"backup_state"`
	CredentialData []byte `json:"credential_data"`
}

func (q *Queries) AcceptAssertionCounter(ctx context.Context, arg AcceptAssertionCounterParams) error {
	_, err := q.db.ExecContext(ctx, acceptAssertionCounter,
		arg.ID,
		arg.SignCount,
		arg.BackupState,
		arg.CredentialData,
	)
	return err
}

const assertionSubject = `-- name: AssertionSubject :one
SELECT user_id FROM auth_pending WHERE digest = $1 AND purpose = $2 AND record_version = 1
`

type AssertionSubjectParams struct {
	Digest  []byte `json:"digest"`
	Purpose int16  `json:"purpose"`
}

func (q *Queries) AssertionSubject(ctx context.Context, arg AssertionSubjectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, assertionSubject, arg.Digest, arg.Purpose)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeAssertion = `-- name: ConsumeAssertion :execrows
DELETE FROM auth_pending WHERE digest = $1 AND purpose = $2 AND revision = $3
`

type ConsumeAssertionParams struct {
	Digest   []byte `json:"digest"`
	Purpose  int16  `json:"purpose"`
	Revision int64  `json:"revision"`
}

func (q *Queries) ConsumeAssertion(ctx context.Context, arg ConsumeAssertionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeAssertion, arg.Digest, arg.Purpose, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAssertion = `-- name: CreateAssertion :exec
INSERT INTO auth_pending(digest,purpose,record_version,user_id,auth_version,rp_id,user_handle,rp_binding,ceremony_data,
required_proof,policy_revision,max_age_us,created_at,expires_at,factor_bindings,actor_id,actor_digest,actor_generation)
VALUES ($1,$2,1,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
`

type CreateAssertionParams struct {
	Digest          []byte         `json:"digest"`
	Purpose         int16          `json:"purpose"`
	UserID          string         `json:"user_id"`
	AuthVersion     int64          `json:"auth_version"`
	RpID            sql.NullString `json:"rp_id"`
	UserHandle      []byte         `json:"user_handle"`
	RpBinding       []byte         `json:"rp_binding"`
	CeremonyData    []byte         `json:"ceremony_data"`
	RequiredProof   int16          `json:"required_proof"`
	PolicyRevision  string         `json:"policy_revision"`
	MaxAgeUs        int64          `json:"max_age_us"`
	CreatedAt       time.Time      `json:"created_at"`
	ExpiresAt       time.Time      `json:"expires_at"`
	FactorBindings  []byte         `json:"factor_bindings"`
	ActorID         string         `json:"actor_id"`
	ActorDigest     []byte         `json:"actor_digest"`
	ActorGeneration int64          `json:"actor_generation"`
}

func (q *Queries) CreateAssertion(ctx context.Context, arg CreateAssertionParams) error {
	_, err := q.db.ExecContext(ctx, createAssertion,
		arg.Digest,
		arg.Purpose,
		arg.UserID,
		arg.AuthVersion,
		arg.RpID,
		arg.UserHandle,
		arg.RpBinding,
		arg.CeremonyData,
		arg.RequiredProof,
		arg.PolicyRevision,
		arg.MaxAgeUs,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.FactorBindings,
		arg.ActorID,
		arg.ActorDigest,
		arg.ActorGeneration,
	)
	return err
}

const lockAssertion = `-- name: LockAssertion :one
SELECT digest, purpose, record_version, user_id, auth_version, rp_id, user_handle, rp_binding, ceremony_data, required_proof, policy_revision, max_age_us, password_at, created_at, expires_at, attempts, revision, lease_until, factor_bindings, actor_id, actor_digest, actor_generation FROM auth_pending WHERE digest = $1 AND purpose = $2 AND record_version = 1 FOR UPDATE
`

type LockAssertionParams struct {
	Digest  []byte `json:"digest"`
	Purpose int16  `json:"purpose"`
}

func (q *Queries) LockAssertion(ctx context.Context, arg LockAssertionParams) (AuthPending, error) {
	row := q.db.QueryRowContext(ctx, lockAssertion, arg.Digest, arg.Purpose)
	var i AuthPending
	err := row.Scan(
		&i.Digest,
		&i.Purpose,
		&i.RecordVersion,
		&i.UserID,
		&i.AuthVersion,
		&i.RpID,
		&i.UserHandle,
		&i.RpBinding,
		&i.CeremonyData,
		&i.RequiredProof,
		&i.PolicyRevision,
		&i.MaxAgeUs,
		&i.PasswordAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.Revision,
		&i.LeaseUntil,
		&i.FactorBindings,
		&i.ActorID,
		&i.ActorDigest,
		&i.ActorGeneration,
	)
	return i, err
}

const lockAuthenticator = `-- name: LockAuthenticator :one
SELECT id, user_id, rp_id, kind, record_version, credential_id, public_key, credential_data, sign_count, backup_eligible, backup_state, user_verified, revision, created_at, replay_revision FROM authenticators WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAuthenticator(ctx context.Context, id string) (Authenticator, error) {
	row := q.db.QueryRowContext(ctx, lockAuthenticator, id)
	var i Authenticator
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RpID,
		&i.Kind,
		&i.RecordVersion,
		&i.CredentialID,
		&i.PublicKey,
		&i.CredentialData,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.UserVerified,
		&i.Revision,
		&i.CreatedAt,
		&i.ReplayRevision,
	)
	return i, err
}

const subjectAuthenticators = `-- name: SubjectAuthenticators :many
SELECT id, user_id, rp_id, kind, record_version, credential_id, public_key, credential_data, sign_count, backup_eligible, backup_state, user_verified, revision, created_at, replay_revision FROM authenticators WHERE user_id = $1 AND rp_id = $2 ORDER BY id LIMIT $3::integer
`

type SubjectAuthenticatorsParams struct {
	UserID  string `json:"user_id"`
	RpID    string `json:"rp_id"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) SubjectAuthenticators(ctx context.Context, arg SubjectAuthenticatorsParams) ([]Authenticator, error) {
	rows, err := q.db.QueryContext(ctx, subjectAuthenticators, arg.UserID, arg.RpID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Authenticator{}
	for rows.Next() {
		var i Authenticator
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RpID,
			&i.Kind,
			&i.RecordVersion,
			&i.CredentialID,
			&i.PublicKey,
			&i.CredentialData,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.UserVerified,
			&i.Revision,
			&i.CreatedAt,
			&i.ReplayRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webAuthnHandle = `-- name: WebAuthnHandle :one

SELECT handle FROM webauthn_subjects WHERE user_id = $1 AND rp_id = $2
`

type WebAuthnHandleParams struct {
	UserID string `json:"user_id"`
	RpID   string `json:"rp_id"`
}

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) WebAuthnHandle(ctx context.Context, arg WebAuthnHandleParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, webAuthnHandle, arg.UserID, arg.RpID)
	var handle []byte
	err := row.Scan(&handle)
	return handle, err
}
