// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential_admission.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const deleteRetiredCredentialAdmissions = `-- name: DeleteRetiredCredentialAdmissions :execrows
WITH retired AS (
 SELECT a.namespace,a.purpose,a.identity_key FROM credential_admissions a
 WHERE a.namespace=$1 AND GREATEST(a.window_end,COALESCE(a.cooldown_until,a.window_end))<=$2::timestamptz
 ORDER BY GREATEST(a.window_end,COALESCE(a.cooldown_until,a.window_end)),a.purpose,a.identity_key
 LIMIT $3::integer FOR UPDATE SKIP LOCKED
)
DELETE FROM credential_admissions USING retired WHERE credential_admissions.namespace=retired.namespace
AND credential_admissions.purpose=retired.purpose AND credential_admissions.identity_key=retired.identity_key
`

type DeleteRetiredCredentialAdmissionsParams struct {
	Namespace    string    `json:"namespace"`
	Now          time.Time `json:"now"`
	CleanupBatch int32     `json:"cleanup_batch"`
}

func (q *Queries) DeleteRetiredCredentialAdmissions(ctx context.Context, arg DeleteRetiredCredentialAdmissionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetiredCredentialAdmissions, arg.Namespace, arg.Now, arg.CleanupBatch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureCredentialAdmissionCapacity = `-- name: EnsureCredentialAdmissionCapacity :exec

INSERT INTO credential_admission_capacity(namespace,key_binding,records,max_records)
VALUES ($1,$2,0,$3) ON CONFLICT DO NOTHING
`

type EnsureCredentialAdmissionCapacityParams struct {
	Namespace  string `json:"namespace"`
	KeyBinding []byte `json:"key_binding"`
	MaxRecords int32  `json:"max_records"`
}

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) EnsureCredentialAdmissionCapacity(ctx context.Context, arg EnsureCredentialAdmissionCapacityParams) error {
	_, err := q.db.ExecContext(ctx, ensureCredentialAdmissionCapacity, arg.Namespace, arg.KeyBinding, arg.MaxRecords)
	return err
}

const insertCredentialAdmission = `-- name: InsertCredentialAdmission :exec
INSERT INTO credential_admissions(namespace,purpose,identity_key,window_start,window_end,cooldown_us,attempt_limit,attempts,cooldown_until)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertCredentialAdmissionParams struct {
	Namespace     string       `json:"namespace"`
	Purpose       int16        `json:"purpose"`
	IdentityKey   []byte       `json:"identity_key"`
	WindowStart   time.Time    `json:"window_start"`
	WindowEnd     time.Time    `json:"window_end"`
	CooldownUs    int64        `json:"cooldown_us"`
	AttemptLimit  int32        `json:"attempt_limit"`
	Attempts      int32        `json:"attempts"`
	CooldownUntil sql.NullTime `json:"cooldown_until"`
}

func (q *Queries) InsertCredentialAdmission(ctx context.Context, arg InsertCredentialAdmissionParams) error {
	_, err := q.db.ExecContext(ctx, insertCredentialAdmission,
		arg.Namespace,
		arg.Purpose,
		arg.IdentityKey,
		arg.WindowStart,
		arg.WindowEnd,
		arg.CooldownUs,
		arg.AttemptLimit,
		arg.Attempts,
		arg.CooldownUntil,
	)
	return err
}

const lockCredentialAdmission = `-- name: LockCredentialAdmission :one
SELECT namespace, purpose, identity_key, window_start, window_end, cooldown_us, attempt_limit, attempts, cooldown_until FROM credential_admissions WHERE namespace=$1 AND purpose=$2 AND identity_key=$3 FOR UPDATE
`

type LockCredentialAdmissionParams struct {
	Namespace   string `json:"namespace"`
	Purpose     int16  `json:"purpose"`
	IdentityKey []byte `json:"identity_key"`
}

func (q *Queries) LockCredentialAdmission(ctx context.Context, arg LockCredentialAdmissionParams) (CredentialAdmission, error) {
	row := q.db.QueryRowContext(ctx, lockCredentialAdmission, arg.Namespace, arg.Purpose, arg.IdentityKey)
	var i CredentialAdmission
	err := row.Scan(
		&i.Namespace,
		&i.Purpose,
		&i.IdentityKey,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CooldownUs,
		&i.AttemptLimit,
		&i.Attempts,
		&i.CooldownUntil,
	)
	return i, err
}

const lockCredentialAdmissionCapacity = `-- name: LockCredentialAdmissionCapacity :one
SELECT namespace, key_binding, records, max_records FROM credential_admission_capacity WHERE namespace=$1 FOR UPDATE
`

func (q *Queries) LockCredentialAdmissionCapacity(ctx context.Context, namespace string) (CredentialAdmissionCapacity, error) {
	row := q.db.QueryRowContext(ctx, lockCredentialAdmissionCapacity, namespace)
	var i CredentialAdmissionCapacity
	err := row.Scan(
		&i.Namespace,
		&i.KeyBinding,
		&i.Records,
		&i.MaxRecords,
	)
	return i, err
}

const updateCredentialAdmission = `-- name: UpdateCredentialAdmission :execrows
UPDATE credential_admissions SET window_start=$4,window_end=$5,cooldown_us=$6,attempt_limit=$7,attempts=$8,cooldown_until=$9
WHERE namespace=$1 AND purpose=$2 AND identity_key=$3
`

type UpdateCredentialAdmissionParams struct {
	Namespace     string       `json:"namespace"`
	Purpose       int16        `json:"purpose"`
	IdentityKey   []byte       `json:"identity_key"`
	WindowStart   time.Time    `json:"window_start"`
	WindowEnd     time.Time    `json:"window_end"`
	CooldownUs    int64        `json:"cooldown_us"`
	AttemptLimit  int32        `json:"attempt_limit"`
	Attempts      int32        `json:"attempts"`
	CooldownUntil sql.NullTime `json:"cooldown_until"`
}

func (q *Queries) UpdateCredentialAdmission(ctx context.Context, arg UpdateCredentialAdmissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCredentialAdmission,
		arg.Namespace,
		arg.Purpose,
		arg.IdentityKey,
		arg.WindowStart,
		arg.WindowEnd,
		arg.CooldownUs,
		arg.AttemptLimit,
		arg.Attempts,
		arg.CooldownUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCredentialAdmissionCapacity = `-- name: UpdateCredentialAdmissionCapacity :execrows
UPDATE credential_admission_capacity SET records=$2,max_records=$3 WHERE namespace=$1
`

type UpdateCredentialAdmissionCapacityParams struct {
	Namespace  string `json:"namespace"`
	Records    int32  `json:"records"`
	MaxRecords int32  `json:"max_records"`
}

func (q *Queries) UpdateCredentialAdmissionCapacity(ctx context.Context, arg UpdateCredentialAdmissionCapacityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCredentialAdmissionCapacity, arg.Namespace, arg.Records, arg.MaxRecords)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
