// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const advanceAuthenticatorVersion = `-- name: AdvanceAuthenticatorVersion :exec
UPDATE users SET auth_version = auth_version + 1, updated_at = $2 WHERE id = $1
`

type AdvanceAuthenticatorVersionParams struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) AdvanceAuthenticatorVersion(ctx context.Context, arg AdvanceAuthenticatorVersionParams) error {
	_, err := q.db.ExecContext(ctx, advanceAuthenticatorVersion, arg.ID, arg.UpdatedAt)
	return err
}

const chargeFactorBudget = `-- name: ChargeFactorBudget :exec
UPDATE auth_factor_budgets SET window_start = $2, attempts = $3, cooldown_until = $4 WHERE user_id = $1
`

type ChargeFactorBudgetParams struct {
	UserID        string       `json:"user_id"`
	WindowStart   time.Time    `json:"window_start"`
	Attempts      int32        `json:"attempts"`
	CooldownUntil sql.NullTime `json:"cooldown_until"`
}

func (q *Queries) ChargeFactorBudget(ctx context.Context, arg ChargeFactorBudgetParams) error {
	_, err := q.db.ExecContext(ctx, chargeFactorBudget,
		arg.UserID,
		arg.WindowStart,
		arg.Attempts,
		arg.CooldownUntil,
	)
	return err
}

const confirmAuthenticator = `-- name: ConfirmAuthenticator :exec
INSERT INTO authenticators(id,user_id,rp_id,kind,record_version,credential_id,public_key,credential_data,sign_count,
backup_eligible,backup_state,user_verified,created_at)
VALUES ($1,$2,$3,1,1,$4,$5,$6,$7,$8,$9,true,$10)
`

type ConfirmAuthenticatorParams struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	RpID           string    `json:"rp_id"`
	CredentialID   []byte    `json:"credential_id"`
	PublicKey      []byte    `json:"public_key"`
	CredentialData []byte    `json:"credential_data"`
	SignCount      int64     `json:"sign_count"`
	BackupEligible bool      `json:"backup_eligible"`
	BackupState    bool      `json:"backup_state"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ConfirmAuthenticator(ctx context.Context, arg ConfirmAuthenticatorParams) error {
	_, err := q.db.ExecContext(ctx, confirmAuthenticator,
		arg.ID,
		arg.UserID,
		arg.RpID,
		arg.CredentialID,
		arg.PublicKey,
		arg.CredentialData,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.CreatedAt,
	)
	return err
}

const countAuthenticators = `-- name: CountAuthenticators :one
SELECT COUNT(*) FROM authenticators WHERE user_id = $1
`

func (q *Queries) CountAuthenticators(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthenticators, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnrollments = `-- name: CountEnrollments :one
SELECT COUNT(*) FROM auth_pending WHERE user_id = $1
`

func (q *Queries) CountEnrollments(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnrollments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollment = `-- name: CreateEnrollment :exec
INSERT INTO auth_pending(digest,purpose,record_version,user_id,auth_version,rp_id,user_handle,ceremony_data,
required_proof,policy_revision,max_age_us,password_at,created_at,expires_at,rp_binding)
VALUES ($1,1,1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type CreateEnrollmentParams struct {
	Digest         []byte       `json:"digest"`
	UserID         string       `json:"user_id"`
	AuthVersion    int64        `json:"auth_version"`
	RpID           string       `json:"rp_id"`
	UserHandle     []byte       `json:"user_handle"`
	CeremonyData   []byte       `json:"ceremony_data"`
	RequiredProof  int16        `json:"required_proof"`
	PolicyRevision string       `json:"policy_revision"`
	MaxAgeUs       int64        `json:"max_age_us"`
	PasswordAt     sql.NullTime `json:"password_at"`
	CreatedAt      time.Time    `json:"created_at"`
	ExpiresAt      time.Time    `json:"expires_at"`
	RpBinding      []byte       `json:"rp_binding"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, createEnrollment,
		arg.Digest,
		arg.UserID,
		arg.AuthVersion,
		arg.RpID,
		arg.UserHandle,
		arg.CeremonyData,
		arg.RequiredProof,
		arg.PolicyRevision,
		arg.MaxAgeUs,
		arg.PasswordAt,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RpBinding,
	)
	return err
}

const deleteExpiredEnrollments = `-- name: DeleteExpiredEnrollments :execrows
WITH expired AS (
 SELECT p.digest FROM auth_pending p WHERE p.expires_at <= clock_timestamp()
 ORDER BY expires_at,digest LIMIT $1::integer FOR UPDATE SKIP LOCKED
)
DELETE FROM auth_pending USING expired WHERE auth_pending.digest = expired.digest
`

func (q *Queries) DeleteExpiredEnrollments(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredEnrollments, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubjectEnrollments = `-- name: DeleteSubjectEnrollments :exec
DELETE FROM auth_pending WHERE user_id = $1
`

func (q *Queries) DeleteSubjectEnrollments(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSubjectEnrollments, userID)
	return err
}

const enrollmentSubject = `-- name: EnrollmentSubject :one
SELECT user_id FROM auth_pending WHERE digest = $1 AND purpose = 1 AND record_version = 1
`

func (q *Queries) EnrollmentSubject(ctx context.Context, digest []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, enrollmentSubject, digest)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const ensureFactorBudget = `-- name: EnsureFactorBudget :exec
INSERT INTO auth_factor_budgets(user_id,window_start,attempts) VALUES ($1,$2,0) ON CONFLICT DO NOTHING
`

type EnsureFactorBudgetParams struct {
	UserID      string    `json:"user_id"`
	WindowStart time.Time `json:"window_start"`
}

func (q *Queries) EnsureFactorBudget(ctx context.Context, arg EnsureFactorBudgetParams) error {
	_, err := q.db.ExecContext(ctx, ensureFactorBudget, arg.UserID, arg.WindowStart)
	return err
}

const ensureWebAuthnHandle = `-- name: EnsureWebAuthnHandle :one

INSERT INTO webauthn_subjects(user_id,rp_id,handle) VALUES ($1,$2,$3)
ON CONFLICT (user_id,rp_id) DO UPDATE SET rp_id = EXCLUDED.rp_id RETURNING handle
`

type EnsureWebAuthnHandleParams struct {
	UserID string `json:"user_id"`
	RpID   string `json:"rp_id"`
	Handle []byte `json:"handle"`
}

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) EnsureWebAuthnHandle(ctx context.Context, arg EnsureWebAuthnHandleParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, ensureWebAuthnHandle, arg.UserID, arg.RpID, arg.Handle)
	var handle []byte
	err := row.Scan(&handle)
	return handle, err
}

const leaseEnrollment = `-- name: LeaseEnrollment :exec
UPDATE auth_pending SET attempts = attempts + 1, revision = revision + 1, lease_until = $2 WHERE digest = $1
`

type LeaseEnrollmentParams struct {
	Digest     []byte       `json:"digest"`
	LeaseUntil sql.NullTime `json:"lease_until"`
}

func (q *Queries) LeaseEnrollment(ctx context.Context, arg LeaseEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, leaseEnrollment, arg.Digest, arg.LeaseUntil)
	return err
}

const lockEnrollment = `-- name: LockEnrollment :one
SELECT digest, purpose, record_version, user_id, auth_version, rp_id, user_handle, rp_binding, ceremony_data, required_proof, policy_revision, max_age_us, password_at, created_at, expires_at, attempts, revision, lease_until, factor_bindings, actor_id, actor_digest, actor_generation FROM auth_pending WHERE digest = $1 AND purpose = 1 AND record_version = 1 FOR UPDATE
`

func (q *Queries) LockEnrollment(ctx context.Context, digest []byte) (AuthPending, error) {
	row := q.db.QueryRowContext(ctx, lockEnrollment, digest)
	var i AuthPending
	err := row.Scan(
		&i.Digest,
		&i.Purpose,
		&i.RecordVersion,
		&i.UserID,
		&i.AuthVersion,
		&i.RpID,
		&i.UserHandle,
		&i.RpBinding,
		&i.CeremonyData,
		&i.RequiredProof,
		&i.PolicyRevision,
		&i.MaxAgeUs,
		&i.PasswordAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.Revision,
		&i.LeaseUntil,
		&i.FactorBindings,
		&i.ActorID,
		&i.ActorDigest,
		&i.ActorGeneration,
	)
	return i, err
}

const lockFactorBudget = `-- name: LockFactorBudget :one
SELECT user_id, window_start, attempts, cooldown_until FROM auth_factor_budgets WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) LockFactorBudget(ctx context.Context, userID string) (AuthFactorBudget, error) {
	row := q.db.QueryRowContext(ctx, lockFactorBudget, userID)
	var i AuthFactorBudget
	err := row.Scan(
		&i.UserID,
		&i.WindowStart,
		&i.Attempts,
		&i.CooldownUntil,
	)
	return i, err
}

const reclaimSubjectEnrollments = `-- name: ReclaimSubjectEnrollments :execrows
WITH expired AS (
 SELECT p.digest FROM auth_pending p WHERE p.user_id = $1 AND p.expires_at <= clock_timestamp()
 ORDER BY digest LIMIT 10 FOR UPDATE
)
DELETE FROM auth_pending USING expired WHERE auth_pending.digest = expired.digest
`

func (q *Queries) ReclaimSubjectEnrollments(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimSubjectEnrollments, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseEnrollment = `-- name: ReleaseEnrollment :exec
UPDATE auth_pending SET lease_until = NULL WHERE digest = $1 AND revision = $2
`

type ReleaseEnrollmentParams struct {
	Digest   []byte `json:"digest"`
	Revision int64  `json:"revision"`
}

func (q *Queries) ReleaseEnrollment(ctx context.Context, arg ReleaseEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, releaseEnrollment, arg.Digest, arg.Revision)
	return err
}
