// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factor_control.sql

package dal

import (
	"context"
	"time"
)

const countFactorSetups = `-- name: CountFactorSetups :one
SELECT COUNT(*) FROM auth_pending WHERE user_id = $1 AND purpose IN (1,4,7)
`

func (q *Queries) CountFactorSetups(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFactorSetups, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lockManagedAuthenticator = `-- name: LockManagedAuthenticator :one
SELECT id, user_id, rp_id, kind, record_version, credential_id, public_key, credential_data, sign_count, backup_eligible, backup_state, user_verified, revision, created_at, replay_revision FROM authenticators WHERE user_id = $1 AND id = $2 FOR UPDATE
`

type LockManagedAuthenticatorParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) LockManagedAuthenticator(ctx context.Context, arg LockManagedAuthenticatorParams) (Authenticator, error) {
	row := q.db.QueryRowContext(ctx, lockManagedAuthenticator, arg.UserID, arg.ID)
	var i Authenticator
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RpID,
		&i.Kind,
		&i.RecordVersion,
		&i.CredentialID,
		&i.PublicKey,
		&i.CredentialData,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.UserVerified,
		&i.Revision,
		&i.CreatedAt,
		&i.ReplayRevision,
	)
	return i, err
}

const removeTOTPFactor = `-- name: RemoveTOTPFactor :execrows
DELETE FROM totp_authenticators t WHERE t.user_id = $1 AND id = $2 AND revision = $3
`

type RemoveTOTPFactorParams struct {
	UserID   string `json:"user_id"`
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) RemoveTOTPFactor(ctx context.Context, arg RemoveTOTPFactorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeTOTPFactor, arg.UserID, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeWebAuthnFactor = `-- name: RemoveWebAuthnFactor :execrows
DELETE FROM authenticators a WHERE a.user_id = $1 AND id = $2 AND revision = $3
`

type RemoveWebAuthnFactorParams struct {
	UserID   string `json:"user_id"`
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) RemoveWebAuthnFactor(ctx context.Context, arg RemoveWebAuthnFactorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeWebAuthnFactor, arg.UserID, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const safeFactors = `-- name: SafeFactors :many

SELECT id, 1::smallint AS kind, revision, created_at, backup_eligible, backup_state FROM authenticators a WHERE a.user_id = $1
UNION ALL
SELECT id, 2::smallint AS kind, revision, created_at, false, false FROM totp_authenticators t WHERE t.user_id = $1
ORDER BY id LIMIT 21
`

type SafeFactorsRow struct {
	ID             string    `json:"id"`
	Kind           int16     `json:"kind"`
	Revision       int64     `json:"revision"`
	CreatedAt      time.Time `json:"created_at"`
	BackupEligible bool      `json:"backup_eligible"`
	BackupState    bool      `json:"backup_state"`
}

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) SafeFactors(ctx context.Context, userID string) ([]SafeFactorsRow, error) {
	rows, err := q.db.QueryContext(ctx, safeFactors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SafeFactorsRow{}
	for rows.Next() {
		var i SafeFactorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Revision,
			&i.CreatedAt,
			&i.BackupEligible,
			&i.BackupState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
