// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fallback.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const acceptTOTPStep = `-- name: AcceptTOTPStep :execrows
UPDATE totp_authenticators SET accepted_step = $2, replay_revision = replay_revision + 1
WHERE id = $1 AND accepted_step < $2 AND replay_revision < 9223372036854775807
`

type AcceptTOTPStepParams struct {
	ID           string `json:"id"`
	AcceptedStep int64  `json:"accepted_step"`
}

func (q *Queries) AcceptTOTPStep(ctx context.Context, arg AcceptTOTPStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptTOTPStep, arg.ID, arg.AcceptedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeBackupCode = `-- name: ConsumeBackupCode :execrows
DELETE FROM backup_codes WHERE id = $1 AND set_id = $2
`

type ConsumeBackupCodeParams struct {
	ID    string `json:"id"`
	SetID string `json:"set_id"`
}

func (q *Queries) ConsumeBackupCode(ctx context.Context, arg ConsumeBackupCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeBackupCode, arg.ID, arg.SetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createBackupCode = `-- name: CreateBackupCode :exec
INSERT INTO backup_codes(id,set_id,verifier) VALUES ($1,$2,$3)
`

type CreateBackupCodeParams struct {
	ID       string `json:"id"`
	SetID    string `json:"set_id"`
	Verifier string `json:"verifier"`
}

func (q *Queries) CreateBackupCode(ctx context.Context, arg CreateBackupCodeParams) error {
	_, err := q.db.ExecContext(ctx, createBackupCode, arg.ID, arg.SetID, arg.Verifier)
	return err
}

const createBackupSet = `-- name: CreateBackupSet :exec
INSERT INTO backup_sets(id,user_id,created_at) VALUES ($1,$2,$3)
`

type CreateBackupSetParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateBackupSet(ctx context.Context, arg CreateBackupSetParams) error {
	_, err := q.db.ExecContext(ctx, createBackupSet, arg.ID, arg.UserID, arg.CreatedAt)
	return err
}

const createFallback = `-- name: CreateFallback :exec
INSERT INTO auth_pending(digest,purpose,user_id,record_version,auth_version,rp_id,user_handle,rp_binding,ceremony_data,
required_proof,policy_revision,max_age_us,password_at,created_at,expires_at,actor_id,actor_digest,actor_generation)
VALUES ($1,$2,$3,1,$4,NULL,'',decode(repeat('00',32),'hex'),$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
`

type CreateFallbackParams struct {
	Digest          []byte       `json:"digest"`
	Purpose         int16        `json:"purpose"`
	UserID          string       `json:"user_id"`
	AuthVersion     int64        `json:"auth_version"`
	CeremonyData    []byte       `json:"ceremony_data"`
	RequiredProof   int16        `json:"required_proof"`
	PolicyRevision  string       `json:"policy_revision"`
	MaxAgeUs        int64        `json:"max_age_us"`
	PasswordAt      sql.NullTime `json:"password_at"`
	CreatedAt       time.Time    `json:"created_at"`
	ExpiresAt       time.Time    `json:"expires_at"`
	ActorID         string       `json:"actor_id"`
	ActorDigest     []byte       `json:"actor_digest"`
	ActorGeneration int64        `json:"actor_generation"`
}

func (q *Queries) CreateFallback(ctx context.Context, arg CreateFallbackParams) error {
	_, err := q.db.ExecContext(ctx, createFallback,
		arg.Digest,
		arg.Purpose,
		arg.UserID,
		arg.AuthVersion,
		arg.CeremonyData,
		arg.RequiredProof,
		arg.PolicyRevision,
		arg.MaxAgeUs,
		arg.PasswordAt,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ActorID,
		arg.ActorDigest,
		arg.ActorGeneration,
	)
	return err
}

const createTOTP = `-- name: CreateTOTP :exec
INSERT INTO totp_authenticators(id,user_id,key_id,envelope,accepted_step,created_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type CreateTOTPParams struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	KeyID        string    `json:"key_id"`
	Envelope     []byte    `json:"envelope"`
	AcceptedStep int64     `json:"accepted_step"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateTOTP(ctx context.Context, arg CreateTOTPParams) error {
	_, err := q.db.ExecContext(ctx, createTOTP,
		arg.ID,
		arg.UserID,
		arg.KeyID,
		arg.Envelope,
		arg.AcceptedStep,
		arg.CreatedAt,
	)
	return err
}

const deleteBackupSet = `-- name: DeleteBackupSet :exec
DELETE FROM backup_sets WHERE user_id = $1
`

func (q *Queries) DeleteBackupSet(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupSet, userID)
	return err
}

const lockBackupCode = `-- name: LockBackupCode :one
SELECT backup_codes.id, backup_codes.set_id, backup_codes.verifier, backup_sets.revision
FROM backup_codes JOIN backup_sets ON backup_sets.id = backup_codes.set_id
WHERE backup_sets.user_id = $1 AND backup_codes.id = $2 FOR UPDATE OF backup_codes
`

type LockBackupCodeParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type LockBackupCodeRow struct {
	ID       string `json:"id"`
	SetID    string `json:"set_id"`
	Verifier string `json:"verifier"`
	Revision int64  `json:"revision"`
}

func (q *Queries) LockBackupCode(ctx context.Context, arg LockBackupCodeParams) (LockBackupCodeRow, error) {
	row := q.db.QueryRowContext(ctx, lockBackupCode, arg.UserID, arg.ID)
	var i LockBackupCodeRow
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Verifier,
		&i.Revision,
	)
	return i, err
}

const lockBackupSet = `-- name: LockBackupSet :one
SELECT id, user_id, revision, created_at FROM backup_sets WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) LockBackupSet(ctx context.Context, userID string) (BackupSet, error) {
	row := q.db.QueryRowContext(ctx, lockBackupSet, userID)
	var i BackupSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const lockTOTP = `-- name: LockTOTP :one

SELECT id, user_id, record_version, key_id, envelope, accepted_step, revision, replay_revision, created_at FROM totp_authenticators WHERE user_id = $1 FOR UPDATE
`

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) LockTOTP(ctx context.Context, userID string) (TotpAuthenticator, error) {
	row := q.db.QueryRowContext(ctx, lockTOTP, userID)
	var i TotpAuthenticator
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordVersion,
		&i.KeyID,
		&i.Envelope,
		&i.AcceptedStep,
		&i.Revision,
		&i.ReplayRevision,
		&i.CreatedAt,
	)
	return i, err
}
