// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dal

import (
	"database/sql"
	"time"
)

type AuthFactorBudget struct {
	UserID        string       `json:"user_id"`
	WindowStart   time.Time    `json:"window_start"`
	Attempts      int32        `json:"attempts"`
	CooldownUntil sql.NullTime `json:"cooldown_until"`
}

type AuthPending struct {
	Digest         []byte       `json:"digest"`
	Purpose        int16        `json:"purpose"`
	RecordVersion  int16        `json:"record_version"`
	UserID         string       `json:"user_id"`
	AuthVersion    int64        `json:"auth_version"`
	RpID           string       `json:"rp_id"`
	UserHandle     []byte       `json:"user_handle"`
	RpBinding      []byte       `json:"rp_binding"`
	CeremonyData   []byte       `json:"ceremony_data"`
	RequiredProof  int16        `json:"required_proof"`
	PolicyRevision string       `json:"policy_revision"`
	MaxAgeUs       int64        `json:"max_age_us"`
	PasswordAt     time.Time    `json:"password_at"`
	CreatedAt      time.Time    `json:"created_at"`
	ExpiresAt      time.Time    `json:"expires_at"`
	Attempts       int32        `json:"attempts"`
	Revision       int64        `json:"revision"`
	LeaseUntil     sql.NullTime `json:"lease_until"`
}

type Session struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	TokenDigest     []byte    `json:"token_digest"`
	AuthVersion     int64     `json:"auth_version"`
	PolicyRevision  string    `json:"policy_revision"`
	Generation      int64     `json:"generation"`
	ProofMethod     int16     `json:"proof_method"`
	ProofVerifiedAt time.Time `json:"proof_verified_at"`
	AuthenticatedAt time.Time `json:"authenticated_at"`
	CreatedAt       time.Time `json:"created_at"`
	LastActivityAt  time.Time `json:"last_activity_at"`
	ExpiresAt       time.Time `json:"expires_at"`
	InactivityUs    int64     `json:"inactivity_us"`
}

type TodoItem struct {
	ID          string       `json:"id"`
	ListID      string       `json:"list_id"`
	Text        string       `json:"text"`
	Completed   bool         `json:"completed"`
	CreatedAt   time.Time    `json:"created_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

type TodoList struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	AuthVersion  int64     `json:"auth_version"`
	Roles        []string  `json:"roles"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
