// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTodoItem(ctx context.Context, id string) error
	DeleteTodoItemsByListID(ctx context.Context, listID string) error
	DeleteTodoList(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetTodoItemByID(ctx context.Context, id string) (TodoItem, error)
	GetTodoItemsByListID(ctx context.Context, listID string) ([]TodoItem, error)
	GetTodoListByUserID(ctx context.Context, userID string) (TodoList, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserForAuth(ctx context.Context, id string) (User, error)
	InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) error
	ListUsers(ctx context.Context) ([]User, error)
	ReplacePassword(ctx context.Context, arg ReplacePasswordParams) (User, error)
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
	UpdateUserRoles(ctx context.Context, arg UpdateUserRolesParams) error
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	UpsertTodoList(ctx context.Context, arg UpsertTodoListParams) error
}

var _ Querier = (*Queries)(nil)
