// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dal

import (
	"context"
	"time"
)

type Querier interface {
	AcceptAssertionCounter(ctx context.Context, arg AcceptAssertionCounterParams) error
	AcceptTOTPStep(ctx context.Context, arg AcceptTOTPStepParams) (int64, error)
	AdvanceAuthenticatorVersion(ctx context.Context, arg AdvanceAuthenticatorVersionParams) error
	AssertionSubject(ctx context.Context, arg AssertionSubjectParams) (string, error)
	ChargeFactorBudget(ctx context.Context, arg ChargeFactorBudgetParams) error
	ConfirmAuthenticator(ctx context.Context, arg ConfirmAuthenticatorParams) error
	ConsumeAssertion(ctx context.Context, arg ConsumeAssertionParams) (int64, error)
	ConsumeBackupCode(ctx context.Context, arg ConsumeBackupCodeParams) (int64, error)
	CountAuthenticators(ctx context.Context, userID string) (int64, error)
	CountEnrollments(ctx context.Context, userID string) (int64, error)
	CountFactorSetups(ctx context.Context, userID string) (int64, error)
	CountSubjectSessions(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAssertion(ctx context.Context, arg CreateAssertionParams) error
	CreateBackupCode(ctx context.Context, arg CreateBackupCodeParams) error
	CreateBackupSet(ctx context.Context, arg CreateBackupSetParams) error
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) error
	CreateFallback(ctx context.Context, arg CreateFallbackParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTOTP(ctx context.Context, arg CreateTOTPParams) error
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBackupSet(ctx context.Context, userID string) error
	DeleteExpiredEnrollments(ctx context.Context, dollar_1 int32) (int64, error)
	DeleteExpiredSessions(ctx context.Context, dollar_1 int32) (int64, error)
	DeleteSession(ctx context.Context, tokenDigest []byte) (int64, error)
	DeleteSubjectEnrollments(ctx context.Context, userID string) error
	DeleteTodoItem(ctx context.Context, id string) error
	DeleteTodoItemsByListID(ctx context.Context, listID string) error
	DeleteTodoList(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	EnrollmentSubject(ctx context.Context, digest []byte) (string, error)
	EnsureFactorBudget(ctx context.Context, arg EnsureFactorBudgetParams) error
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	EnsureWebAuthnHandle(ctx context.Context, arg EnsureWebAuthnHandleParams) ([]byte, error)
	GetSessionByDigest(ctx context.Context, tokenDigest []byte) (Session, error)
	GetSessionForUpdate(ctx context.Context, tokenDigest []byte) (Session, error)
	GetTodoItemByID(ctx context.Context, id string) (TodoItem, error)
	GetTodoItemsByListID(ctx context.Context, listID string) ([]TodoItem, error)
	GetTodoListByUserID(ctx context.Context, userID string) (TodoList, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserForAuth(ctx context.Context, id string) (User, error)
	InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) error
	LeaseEnrollment(ctx context.Context, arg LeaseEnrollmentParams) error
	ListSubjectSessions(ctx context.Context, arg ListSubjectSessionsParams) ([]Session, error)
	ListUsers(ctx context.Context) ([]User, error)
	LockAssertion(ctx context.Context, arg LockAssertionParams) (AuthPending, error)
	LockAuthenticator(ctx context.Context, id string) (Authenticator, error)
	LockBackupCode(ctx context.Context, arg LockBackupCodeParams) (LockBackupCodeRow, error)
	LockBackupSet(ctx context.Context, userID string) (BackupSet, error)
	LockEnrollment(ctx context.Context, digest []byte) (AuthPending, error)
	LockFactorBudget(ctx context.Context, userID string) (AuthFactorBudget, error)
	LockManagedAuthenticator(ctx context.Context, arg LockManagedAuthenticatorParams) (Authenticator, error)
	LockSubjectSessions(ctx context.Context, userID string) ([]string, error)
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	LockTOTP(ctx context.Context, userID string) (TotpAuthenticator, error)
	ReclaimSubjectEnrollments(ctx context.Context, userID string) (int64, error)
	ReclaimSubjectSessions(ctx context.Context, userID string) (int64, error)
	ReleaseEnrollment(ctx context.Context, arg ReleaseEnrollmentParams) error
	RemoveTOTPFactor(ctx context.Context, arg RemoveTOTPFactorParams) (int64, error)
	RemoveWebAuthnFactor(ctx context.Context, arg RemoveWebAuthnFactorParams) (int64, error)
	ReplacePassword(ctx context.Context, arg ReplacePasswordParams) (User, error)
	RevokeSubjectSessions(ctx context.Context, arg RevokeSubjectSessionsParams) (int64, error)
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	SafeFactors(ctx context.Context, arg SafeFactorsParams) ([]SafeFactorsRow, error)
	SessionClock(ctx context.Context) (time.Time, error)
	SubjectAuthenticators(ctx context.Context, arg SubjectAuthenticatorsParams) ([]Authenticator, error)
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) (Session, error)
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
	UpdateUserRoles(ctx context.Context, arg UpdateUserRolesParams) error
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	UpsertTodoList(ctx context.Context, arg UpsertTodoListParams) error
	// SPDX-FileCopyrightText: 2026 Adrian PK
	// SPDX-License-Identifier: Apache-2.0
	//
	// This file is part of Hatmax. See LICENSE for license terms.
	WebAuthnHandle(ctx context.Context, arg WebAuthnHandleParams) ([]byte, error)
}

var _ Querier = (*Queries)(nil)
