// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const attemptRecoveryNotice = `-- name: AttemptRecoveryNotice :exec
UPDATE recovery_notices SET attempts=attempts+1 WHERE id=$1
`

func (q *Queries) AttemptRecoveryNotice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, attemptRecoveryNotice, id)
	return err
}

const chargeMailboxToken = `-- name: ChargeMailboxToken :exec
UPDATE mailbox_tokens SET attempts=attempts+1,revision=revision+1 WHERE id=$1
`

func (q *Queries) ChargeMailboxToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, chargeMailboxToken, id)
	return err
}

const chargeRecoveryBudget = `-- name: ChargeRecoveryBudget :exec
UPDATE recovery_budgets SET window_start=$3,attempts=$4 WHERE user_id=$1 AND kind=$2
`

type ChargeRecoveryBudgetParams struct {
	UserID      string    `json:"user_id"`
	Kind        int16     `json:"kind"`
	WindowStart time.Time `json:"window_start"`
	Attempts    int32     `json:"attempts"`
}

func (q *Queries) ChargeRecoveryBudget(ctx context.Context, arg ChargeRecoveryBudgetParams) error {
	_, err := q.db.ExecContext(ctx, chargeRecoveryBudget,
		arg.UserID,
		arg.Kind,
		arg.WindowStart,
		arg.Attempts,
	)
	return err
}

const consumeMailboxToken = `-- name: ConsumeMailboxToken :exec
UPDATE mailbox_tokens SET consumed_at=$2,lease_until=NULL,revision=revision+1 WHERE id=$1
`

type ConsumeMailboxTokenParams struct {
	ID         string       `json:"id"`
	ConsumedAt sql.NullTime `json:"consumed_at"`
}

func (q *Queries) ConsumeMailboxToken(ctx context.Context, arg ConsumeMailboxTokenParams) error {
	_, err := q.db.ExecContext(ctx, consumeMailboxToken, arg.ID, arg.ConsumedAt)
	return err
}

const countRecoveryNotices = `-- name: CountRecoveryNotices :one
SELECT count(*) FROM recovery_notices WHERE user_id=$1
`

func (q *Queries) CountRecoveryNotices(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecoveryNotices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryNotice = `-- name: CreateRecoveryNotice :exec
INSERT INTO recovery_notices(id,user_id,kind,destination,created_at) VALUES ($1,$2,$3,$4,$5)
`

type CreateRecoveryNoticeParams struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Kind        int16     `json:"kind"`
	Destination string    `json:"destination"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateRecoveryNotice(ctx context.Context, arg CreateRecoveryNoticeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryNotice,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Destination,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredMailboxTokens = `-- name: DeleteExpiredMailboxTokens :execrows
WITH retired AS (
 SELECT id FROM mailbox_tokens WHERE COALESCE(consumed_at,revoked_at,expires_at)+INTERVAL '24 hours'<=clock_timestamp()
 AND (lease_until IS NULL OR lease_until<=clock_timestamp())
 ORDER BY COALESCE(consumed_at,revoked_at,expires_at),id LIMIT $1::integer FOR UPDATE SKIP LOCKED
)
DELETE FROM mailbox_tokens USING retired WHERE mailbox_tokens.id=retired.id
`

func (q *Queries) DeleteExpiredMailboxTokens(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredMailboxTokens, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deliverRecoveryNotice = `-- name: DeliverRecoveryNotice :exec
UPDATE recovery_notices SET delivered_at=clock_timestamp() WHERE id=$1
`

func (q *Queries) DeliverRecoveryNotice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deliverRecoveryNotice, id)
	return err
}

const ensureRecoveryBudget = `-- name: EnsureRecoveryBudget :exec
INSERT INTO recovery_budgets(user_id,kind,window_start,attempts) VALUES ($1,$2,$3,0) ON CONFLICT DO NOTHING
`

type EnsureRecoveryBudgetParams struct {
	UserID      string    `json:"user_id"`
	Kind        int16     `json:"kind"`
	WindowStart time.Time `json:"window_start"`
}

func (q *Queries) EnsureRecoveryBudget(ctx context.Context, arg EnsureRecoveryBudgetParams) error {
	_, err := q.db.ExecContext(ctx, ensureRecoveryBudget, arg.UserID, arg.Kind, arg.WindowStart)
	return err
}

const issueMailboxToken = `-- name: IssueMailboxToken :exec

INSERT INTO mailbox_tokens(id,user_id,purpose,target,auth_version,policy_revision,secret_digest,created_at,expires_at,attempt_limit)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (user_id,purpose) DO UPDATE SET id=EXCLUDED.id,target=EXCLUDED.target,auth_version=EXCLUDED.auth_version,
policy_revision=EXCLUDED.policy_revision,secret_digest=EXCLUDED.secret_digest,created_at=EXCLUDED.created_at,
expires_at=EXCLUDED.expires_at,attempt_limit=EXCLUDED.attempt_limit,attempts=0,revision=1,lease_until=NULL,consumed_at=NULL,revoked_at=NULL
`

type IssueMailboxTokenParams struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Purpose        int16     `json:"purpose"`
	Target         string    `json:"target"`
	AuthVersion    int64     `json:"auth_version"`
	PolicyRevision string    `json:"policy_revision"`
	SecretDigest   []byte    `json:"secret_digest"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
	AttemptLimit   int32     `json:"attempt_limit"`
}

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) IssueMailboxToken(ctx context.Context, arg IssueMailboxTokenParams) error {
	_, err := q.db.ExecContext(ctx, issueMailboxToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Target,
		arg.AuthVersion,
		arg.PolicyRevision,
		arg.SecretDigest,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AttemptLimit,
	)
	return err
}

const leaseMailboxToken = `-- name: LeaseMailboxToken :exec
UPDATE mailbox_tokens SET lease_until=$2 WHERE id=$1 AND revision=$3
`

type LeaseMailboxTokenParams struct {
	ID         string       `json:"id"`
	LeaseUntil sql.NullTime `json:"lease_until"`
	Revision   int64        `json:"revision"`
}

func (q *Queries) LeaseMailboxToken(ctx context.Context, arg LeaseMailboxTokenParams) error {
	_, err := q.db.ExecContext(ctx, leaseMailboxToken, arg.ID, arg.LeaseUntil, arg.Revision)
	return err
}

const lockMailboxToken = `-- name: LockMailboxToken :one
SELECT id, user_id, purpose, target, auth_version, policy_revision, secret_digest, created_at, expires_at, attempts, attempt_limit, revision, lease_until, consumed_at, revoked_at FROM mailbox_tokens WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockMailboxToken(ctx context.Context, id string) (MailboxToken, error) {
	row := q.db.QueryRowContext(ctx, lockMailboxToken, id)
	var i MailboxToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.AuthVersion,
		&i.PolicyRevision,
		&i.SecretDigest,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.AttemptLimit,
		&i.Revision,
		&i.LeaseUntil,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockRecoveryBudget = `-- name: LockRecoveryBudget :one
SELECT user_id, kind, window_start, attempts FROM recovery_budgets WHERE user_id=$1 AND kind=$2 FOR UPDATE
`

type LockRecoveryBudgetParams struct {
	UserID string `json:"user_id"`
	Kind   int16  `json:"kind"`
}

func (q *Queries) LockRecoveryBudget(ctx context.Context, arg LockRecoveryBudgetParams) (RecoveryBudget, error) {
	row := q.db.QueryRowContext(ctx, lockRecoveryBudget, arg.UserID, arg.Kind)
	var i RecoveryBudget
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.WindowStart,
		&i.Attempts,
	)
	return i, err
}

const lockRecoveryNotices = `-- name: LockRecoveryNotices :many
SELECT id, user_id, kind, destination, created_at, attempts, delivered_at FROM recovery_notices WHERE user_id=$1 AND delivered_at IS NULL AND attempts<5 AND created_at+INTERVAL '7 days'>clock_timestamp()
ORDER BY created_at,id LIMIT $2::integer FOR UPDATE SKIP LOCKED
`

type LockRecoveryNoticesParams struct {
	UserID    string `json:"user_id"`
	PageLimit int32  `json:"page_limit"`
}

func (q *Queries) LockRecoveryNotices(ctx context.Context, arg LockRecoveryNoticesParams) ([]RecoveryNotice, error) {
	rows, err := q.db.QueryContext(ctx, lockRecoveryNotices, arg.UserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryNotice{}
	for rows.Next() {
		var i RecoveryNotice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Destination,
			&i.CreatedAt,
			&i.Attempts,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailboxSubject = `-- name: MailboxSubject :one
SELECT user_id FROM mailbox_tokens WHERE id=$1
`

func (q *Queries) MailboxSubject(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, mailboxSubject, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const reclaimRecoveryNotices = `-- name: ReclaimRecoveryNotices :execrows
WITH retired AS (
 SELECT n.id FROM recovery_notices n WHERE n.user_id=$1 AND (n.delivered_at IS NOT NULL OR n.created_at+INTERVAL '7 days'<=clock_timestamp())
 ORDER BY n.created_at,n.id LIMIT 20 FOR UPDATE
)
DELETE FROM recovery_notices USING retired WHERE recovery_notices.id=retired.id
`

func (q *Queries) ReclaimRecoveryNotices(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimRecoveryNotices, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoveryPasswordFactors = `-- name: RecoveryPasswordFactors :many
SELECT id, 1::smallint AS kind, revision FROM authenticators a WHERE a.user_id=$1
UNION ALL
SELECT id, 2::smallint AS kind, revision FROM totp_authenticators t WHERE t.user_id=$1
ORDER BY id LIMIT 21
`

type RecoveryPasswordFactorsRow struct {
	ID       string `json:"id"`
	Kind     int16  `json:"kind"`
	Revision int64  `json:"revision"`
}

func (q *Queries) RecoveryPasswordFactors(ctx context.Context, userID string) ([]RecoveryPasswordFactorsRow, error) {
	rows, err := q.db.QueryContext(ctx, recoveryPasswordFactors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryPasswordFactorsRow{}
	for rows.Next() {
		var i RecoveryPasswordFactorsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseMailboxToken = `-- name: ReleaseMailboxToken :exec
UPDATE mailbox_tokens SET lease_until=NULL WHERE id=$1 AND revision=$2 AND consumed_at IS NULL AND revoked_at IS NULL
`

type ReleaseMailboxTokenParams struct {
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) ReleaseMailboxToken(ctx context.Context, arg ReleaseMailboxTokenParams) error {
	_, err := q.db.ExecContext(ctx, releaseMailboxToken, arg.ID, arg.Revision)
	return err
}

const revokeSubjectMailboxTokens = `-- name: RevokeSubjectMailboxTokens :exec
UPDATE mailbox_tokens SET revoked_at=$2,lease_until=NULL,revision=revision+1 WHERE user_id=$1 AND consumed_at IS NULL AND revoked_at IS NULL
`

type RevokeSubjectMailboxTokensParams struct {
	UserID    string       `json:"user_id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeSubjectMailboxTokens(ctx context.Context, arg RevokeSubjectMailboxTokensParams) error {
	_, err := q.db.ExecContext(ctx, revokeSubjectMailboxTokens, arg.UserID, arg.RevokedAt)
	return err
}

const verifyCurrentMailbox = `-- name: VerifyCurrentMailbox :exec
UPDATE users SET mailbox_verified_at=$2,auth_version=auth_version+1,updated_at=$2 WHERE id=$1
`

type VerifyCurrentMailboxParams struct {
	ID                string       `json:"id"`
	MailboxVerifiedAt sql.NullTime `json:"mailbox_verified_at"`
}

func (q *Queries) VerifyCurrentMailbox(ctx context.Context, arg VerifyCurrentMailboxParams) error {
	_, err := q.db.ExecContext(ctx, verifyCurrentMailbox, arg.ID, arg.MailboxVerifiedAt)
	return err
}
