// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dal

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_digest, auth_version, generation, authenticated_at, created_at, last_activity_at, expires_at, inactivity_us)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, user_id, token_digest, auth_version, generation, authenticated_at, created_at, last_activity_at, expires_at, inactivity_us
`

type CreateSessionParams struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	TokenDigest     []byte    `json:"token_digest"`
	AuthVersion     int64     `json:"auth_version"`
	Generation      int64     `json:"generation"`
	AuthenticatedAt time.Time `json:"authenticated_at"`
	CreatedAt       time.Time `json:"created_at"`
	LastActivityAt  time.Time `json:"last_activity_at"`
	ExpiresAt       time.Time `json:"expires_at"`
	InactivityUs    int64     `json:"inactivity_us"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenDigest,
		arg.AuthVersion,
		arg.Generation,
		arg.AuthenticatedAt,
		arg.CreatedAt,
		arg.LastActivityAt,
		arg.ExpiresAt,
		arg.InactivityUs,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.AuthVersion,
		&i.Generation,
		&i.AuthenticatedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.InactivityUs,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, roles, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, auth_version, roles, active, created_at, updated_at
`

type CreateUserParams struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Roles        []string  `json:"roles"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// SPDX-FileCopyrightText: 2026 Adrian PK
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of Hatmax. See LICENSE for license terms.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		pq.Array(arg.Roles),
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AuthVersion,
		pq.Array(&i.Roles),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
WITH expired AS (
    SELECT id FROM sessions
    WHERE expires_at <= clock_timestamp()
       OR last_activity_at + inactivity_us * INTERVAL '1 microsecond' <= clock_timestamp()
    ORDER BY expires_at, id LIMIT $1::integer FOR UPDATE SKIP LOCKED
)
DELETE FROM sessions USING expired WHERE sessions.id = expired.id
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token_digest = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenDigest []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, tokenDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByDigest = `-- name: GetSessionByDigest :one
SELECT id, user_id, token_digest, auth_version, generation, authenticated_at, created_at, last_activity_at, expires_at, inactivity_us
FROM sessions WHERE token_digest = $1
`

func (q *Queries) GetSessionByDigest(ctx context.Context, tokenDigest []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByDigest, tokenDigest)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.AuthVersion,
		&i.Generation,
		&i.AuthenticatedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.InactivityUs,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, token_digest, auth_version, generation, authenticated_at, created_at, last_activity_at, expires_at, inactivity_us
FROM sessions WHERE token_digest = $1 FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, tokenDigest []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionForUpdate, tokenDigest)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.AuthVersion,
		&i.Generation,
		&i.AuthenticatedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.InactivityUs,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, auth_version, roles, active, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AuthVersion,
		pq.Array(&i.Roles),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, auth_version, roles, active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AuthVersion,
		pq.Array(&i.Roles),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id, email, password_hash, auth_version, roles, active, created_at, updated_at
FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForAuth(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForAuth, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AuthVersion,
		pq.Array(&i.Roles),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, auth_version, roles, active, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.AuthVersion,
			pq.Array(&i.Roles),
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePassword = `-- name: ReplacePassword :one
UPDATE users SET password_hash = $2, auth_version = auth_version + 1, updated_at = $3
WHERE id = $1
RETURNING id, email, password_hash, auth_version, roles, active, created_at, updated_at
`

type ReplacePasswordParams struct {
	ID           string    `json:"id"`
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ReplacePassword(ctx context.Context, arg ReplacePasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, replacePassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AuthVersion,
		pq.Array(&i.Roles),
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionClock = `-- name: SessionClock :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) SessionClock(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, sessionClock)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :one
UPDATE sessions SET last_activity_at = $2 WHERE id = $1
RETURNING id, user_id, token_digest, auth_version, generation, authenticated_at, created_at, last_activity_at, expires_at, inactivity_us
`

type UpdateSessionActivityParams struct {
	ID             string    `json:"id"`
	LastActivityAt time.Time `json:"last_activity_at"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionActivity, arg.ID, arg.LastActivityAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.AuthVersion,
		&i.Generation,
		&i.AuthenticatedAt,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.InactivityUs,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users
SET active = $2, updated_at = $3, auth_version = auth_version + 1
WHERE id = $1
`

type UpdateUserActiveParams struct {
	ID        string    `json:"id"`
	Active    bool      `json:"active"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateUserActive, arg.ID, arg.Active, arg.UpdatedAt)
	return err
}

const updateUserRoles = `-- name: UpdateUserRoles :exec
UPDATE users
SET roles = $2, updated_at = $3, auth_version = auth_version + 1
WHERE id = $1
`

type UpdateUserRolesParams struct {
	ID        string    `json:"id"`
	Roles     []string  `json:"roles"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserRoles(ctx context.Context, arg UpdateUserRolesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRoles, arg.ID, pq.Array(arg.Roles), arg.UpdatedAt)
	return err
}
