// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTodoItem(ctx context.Context, id string) error
	DeleteTodoItemsByListID(ctx context.Context, listID string) error
	DeleteTodoList(ctx context.Context, id string) error
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetTodoItemByID(ctx context.Context, id string) (TodoItem, error)
	GetTodoItemsByListID(ctx context.Context, listID string) ([]TodoItem, error)
	GetTodoListByUserID(ctx context.Context, userID string) (TodoList, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) error
	ListUsers(ctx context.Context) ([]User, error)
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
	UpdateUserRoles(ctx context.Context, arg UpdateUserRolesParams) error
	UpsertTodoList(ctx context.Context, arg UpsertTodoListParams) error
}

var _ Querier = (*Queries)(nil)
