// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteTodoItem = `-- name: DeleteTodoItem :exec
DELETE FROM todo_items WHERE id = $1
`

func (q *Queries) DeleteTodoItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoItem, id)
	return err
}

const deleteTodoItemsByListID = `-- name: DeleteTodoItemsByListID :exec
DELETE FROM todo_items WHERE list_id = $1
`

func (q *Queries) DeleteTodoItemsByListID(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoItemsByListID, listID)
	return err
}

const deleteTodoList = `-- name: DeleteTodoList :exec
DELETE FROM todo_lists WHERE id = $1
`

func (q *Queries) DeleteTodoList(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoList, id)
	return err
}

const getTodoItemByID = `-- name: GetTodoItemByID :one
SELECT id, list_id, text, completed, created_at, completed_at
FROM todo_items
WHERE id = $1
`

func (q *Queries) GetTodoItemByID(ctx context.Context, id string) (TodoItem, error) {
	row := q.db.QueryRowContext(ctx, getTodoItemByID, id)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Text,
		&i.Completed,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTodoItemsByListID = `-- name: GetTodoItemsByListID :many
SELECT id, list_id, text, completed, created_at, completed_at
FROM todo_items
WHERE list_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTodoItemsByListID(ctx context.Context, listID string) ([]TodoItem, error) {
	rows, err := q.db.QueryContext(ctx, getTodoItemsByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoItem{}
	for rows.Next() {
		var i TodoItem
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Text,
			&i.Completed,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoListByUserID = `-- name: GetTodoListByUserID :one
SELECT id, user_id, created_at, updated_at
FROM todo_lists
WHERE user_id = $1
`

func (q *Queries) GetTodoListByUserID(ctx context.Context, userID string) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, getTodoListByUserID, userID)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTodoItem = `-- name: InsertTodoItem :exec
INSERT INTO todo_items (id, list_id, text, completed, created_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTodoItemParams struct {
	ID          string       `json:"id"`
	ListID      string       `json:"list_id"`
	Text        string       `json:"text"`
	Completed   bool         `json:"completed"`
	CreatedAt   time.Time    `json:"created_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) InsertTodoItem(ctx context.Context, arg InsertTodoItemParams) error {
	_, err := q.db.ExecContext(ctx, insertTodoItem,
		arg.ID,
		arg.ListID,
		arg.Text,
		arg.Completed,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}

const updateTodoItem = `-- name: UpdateTodoItem :exec
UPDATE todo_items
SET text = $2, completed = $3, completed_at = $4
WHERE id = $1
`

type UpdateTodoItemParams struct {
	ID          string       `json:"id"`
	Text        string       `json:"text"`
	Completed   bool         `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoItem,
		arg.ID,
		arg.Text,
		arg.Completed,
		arg.CompletedAt,
	)
	return err
}

const upsertTodoList = `-- name: UpsertTodoList :exec
INSERT INTO todo_lists (id, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    updated_at = EXCLUDED.updated_at
`

type UpsertTodoListParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertTodoList(ctx context.Context, arg UpsertTodoListParams) error {
	_, err := q.db.ExecContext(ctx, upsertTodoList,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
