# Default configuration for the service.
# Values can be overridden by environment variables or command-line flags.

server:
  # The port the server will listen on.
  # Env: TODO_SERVER_PORT
  port: ":8085"

database:
  # Path to the SQLite database file.
  # Env: TODO_DATABASE_PATH
  path: "./app.db"
